parameters:
  happyr_mailer.user_class: HappyR\MailerBundle\Services\MailerService.php

services:
  happyr.mailer:
    class: %happyr_mailer.user_class%
    arguments: [@mailer,@templating,{'name':%happyr_mailer.from.name%,'email':%happyr_mailer.from.email%}]