parameters:
  happyr_mailer.user_class: HappyR\MailerBundle\Services\MailerService

services:
  happyr.mailer:
    class: %happyr_mailer.user_class%
    arguments:
      - @mailer
      - @templating
      - @service_container
      - name: %happyr_mailer.from.name%
        email: %happyr_mailer.from.email%
        errorType: %happyr_mailer.error_type%
        fakeRequest: %happyr_mailer.fake_request%