language: php

php:
    - 5.6
    - 7.0
    - 7.1

env:
  - SYMFONY_VERSION=2.7.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-dist

script: phpunit --coverage-text

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*




